/**
 * verifyAddrs-min.php
 *
 *
 * @package   Hospitality HouseKeeper
 * @author    Eric K. Crane <ecrane@nonprofitsoftwarecorp.org>
 * @copyright 2010-2014 <nonprofitsoftwarecorp.org>
 * @license   GPL and MIT
 * @link      https://github.com/ecrane57/Hospitality-HouseKeeper
 */
function verifyAddrs(e){"use strict";var t;$("#zipSearch").dialog({autoOpen:false,resizable:true,width:650,modal:true,title:"Zip Code Search",buttons:{Exit:function(){$(this).dialog("close")}}});$("#txtZipSch").autocomplete({source:function(e,n){t=$.getJSON("ws_admin.php",{zip:e.term,cmd:"schzip"}).done(function(e,r,i){if(i===t){if(e.error){e.value=e.error}n(e)}else{n()}}).fail(function(e,t,n){var r=t+", "+n;alert("Postal code request failed: "+r)})},minLength:3,select:function(e,t){if(!t.item){return}$("#zipSearch").dialog("close");var n=$("#zipSearch").data("hhkindex");var r=$("#zipSearch").data("hhkprefix");$("#"+r+"adrcity"+n).val(t.item.City);$("#"+r+"adrcountry"+n).val("US");$("#"+r+"adrcountry"+n).change();$("#"+r+"adrstate"+n).val(t.item.State);$("#"+r+"adrzip"+n).val(t.item.id)}});$(e).on("click",".hhk-zipsearch",function(){$("#zipSearch").data("hhkprefix",$(this).data("hhkprefix"));$("#zipSearch").data("hhkindex",$(this).data("hhkindex"));$("input#txtZipSch").val("");$("#zipSearch").dialog("open")});$(e).on("change","input.hhk-emailInput",function(){var e=/^[A-Z0-9._%+\-]+@(?:[A-Z0-9]+\.)+[A-Z]{2,4}$/i;if($.trim($(this).val())!==""&&e.test($(this).val())===false){$(this).addClass("ui-state-error")}else{$(this).removeClass("ui-state-error")}});$(e).on("change","input.hhk-phoneInput",function(){var e=/^([\(]{1}[0-9]{3}[\)]{1}[\.| |\-]{0,1}|^[0-9]{3}[\.|\-| ]?)?[0-9]{3}(\.|\-| )?[0-9]{4}$/;var t=/^(?:(?:[\+]?([\d]{1,3}(?:[ ]+|[\-.])))?[(]?([2-9][\d]{2})[\-\/)]?(?:[ ]+)?)?([2-9][0-9]{2})[\-.\/)]?(?:[ ]+)?([\d]{4})(?:(?:[ ]+|[xX]|(i:ext[\.]?)){1,2}([\d]{1,5}))?$/;var n;if($.trim($(this).val())!=""&&e.test($(this).val())===false){$(this).addClass("ui-state-error")}else{$(this).removeClass("ui-state-error");t.lastIndex=0;n=t.exec($(this).val());if(n!=null&&n.length>3){var r="";if(n[1]!=null&&n[1]!=""){r="+"+n[1]}$(this).val(r+"("+n[2]+") "+n[3]+"-"+n[4]);if(n[6]!=null&&n[6]!=""){$(this).next("input").val(n[6])}}}});$(e).on("change","input.ckzip",function(){var e=/^(?:[A-Z]{1,2}[0-9][A-Z0-9]? [0-9][ABD-HJLNP-UW-Z]{2}|[ABCEGHJKLMNPRSTVXY][0-9][A-Z] [0-9][A-Z][0-9]|[0-9]{5}(?:\-[0-9]{4})?)$/i;if($(this).val()!==""&&!e.test($(this).val())){$(this).addClass("ui-state-error")}else{$(this).removeClass("ui-state-error")}})}